export { default as UILoadPanel } from './UILoadPanel';
export { default as UITipPanel } from './UITipPanel';
export { default as UINoviceTutorialPanel } from './UINoviceTutorialPanel';
export { default as UIRecordPanel } from './UIRecordPanel';
export { default as LoadScenePanel } from './LoadScenePanel';
export { default as UISelectPanel } from './UISelectPanel';
export { default as UIFunctionPanel } from './UIFunctionPanel';
export { default as UISubtitlePanel } from './UISubtitlePanel';
export { default as UIProtectiveClothingPanel } from './UIProtectiveClothingPanel';
export { default as TaskMenu } from './TaskMenu';
export { default as UIHistoryTakingPanel } from './UIHistoryTakingPanel';
export { default as UIDisinfectPanel } from './UIDisinfectPanel';
export { default as UIComprehensivePerformanceRecordPanel } from './UIComprehensivePerformanceRecordPanel';
export { default as UITopOptTip } from './UITopOptTip';
export { SettingsPanel } from './SettingsPanel';
export { LogPanel } from './LogPanel';
export { StatsPanel } from './StatsPanel';
